from __future__ import annotations

from datetime import date, datetime, time
from enum import Enum
import inspect
import json
from pathlib import Path
import types
from typing import Any, Literal, Union, get_args, get_origin, get_type_hints

from pydantic import BaseModel

from . import contracts


REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = REPO_ROOT / "backend" / "app" / "generated" / "contracts.schema.json"
TS_PATH = REPO_ROOT / "frontend" / "src" / "core" / "contracts.generated.ts"


def _iter_contract_symbols() -> tuple[list[type[Enum]], list[type[BaseModel]]]:
    enums: list[type[Enum]] = []
    models: list[type[BaseModel]] = []
    for _, obj in contracts.__dict__.items():
        if not inspect.isclass(obj):
            continue
        if obj.__module__ != contracts.__name__:
            continue
        if issubclass(obj, Enum):
            enums.append(obj)
            continue
        if issubclass(obj, BaseModel):
            models.append(obj)
    return enums, models


def _ts_literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _format_union(parts: list[str]) -> str:
    ordered: list[str] = []
    for part in parts:
        if part not in ordered:
            ordered.append(part)
    return " | ".join(ordered) if ordered else "unknown"


def _is_collection_annotation(annotation: Any) -> bool:
    origin = get_origin(annotation)
    return origin in {list, set, frozenset, tuple, dict}


def _ts_for_type(annotation: Any) -> str:
    origin = get_origin(annotation)
    args = get_args(annotation)

    if annotation is Any:
        return "unknown"
    if annotation in {str}:
        return "string"
    if annotation in {int, float}:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation in {datetime, date, time}:
        return "string"
    if annotation is type(None):
        return "null"

    if inspect.isclass(annotation):
        if issubclass(annotation, Enum):
            if annotation.__module__ == contracts.__name__:
                return annotation.__name__
            return _format_union([_ts_literal(member.value) for member in annotation])
        if issubclass(annotation, BaseModel):
            return annotation.__name__

    if origin is Literal:
        return _format_union([_ts_literal(value) for value in args])

    if origin in {list, set, frozenset}:
        inner = _ts_for_type(args[0] if args else Any)
        return f"{inner}[]"

    if origin is tuple:
        if len(args) == 2 and args[1] is Ellipsis:
            return f"{_ts_for_type(args[0])}[]"
        return "[" + ", ".join(_ts_for_type(item) for item in args) + "]"

    if origin is dict:
        value_type = _ts_for_type(args[1] if len(args) > 1 else Any)
        return f"Record<string, {value_type}>"

    if origin in {types.UnionType, Union}:
        return _format_union([_ts_for_type(item) for item in args])

    return "unknown"


def _render_enum(enum_cls: type[Enum]) -> str:
    values = [_ts_literal(member.value) for member in enum_cls]
    return f"export type {enum_cls.__name__} = {_format_union(values)};\n"


def _render_model(model_cls: type[BaseModel]) -> str:
    type_hints = get_type_hints(model_cls, globalns=vars(contracts), include_extras=True)
    lines = [f"export type {model_cls.__name__} = {{"]
    request_model = model_cls.__name__.endswith("Request") or model_cls.__name__.endswith("Body")
    for field_name, field_info in model_cls.model_fields.items():
        annotation = type_hints.get(field_name, field_info.annotation)
        optional = not field_info.is_required() and (request_model or not _is_collection_annotation(annotation))
        ts_type = _ts_for_type(annotation)
        lines.append(f"  {field_name}{'?' if optional else ''}: {ts_type};")
    lines.append("};\n")
    return "\n".join(lines)


def render_typescript() -> str:
    enums, models = _iter_contract_symbols()
    sections = [
        "// This file is generated by the Anvil contract generator. Do not edit by hand.\n",
    ]
    sections.extend(_render_enum(enum_cls) for enum_cls in enums)
    sections.extend(_render_model(model_cls) for model_cls in models)
    return "\n".join(sections).rstrip() + "\n"


def render_schema_bundle() -> str:
    enums, models = _iter_contract_symbols()
    payload = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "module": contracts.__name__,
        "enums": {enum_cls.__name__: [member.value for member in enum_cls] for enum_cls in enums},
        "models": {model_cls.__name__: model_cls.model_json_schema() for model_cls in models},
    }
    return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def write_contract_artifacts() -> dict[str, Path]:
    schema_text = render_schema_bundle()
    ts_text = render_typescript()
    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(schema_text, encoding="utf-8")
    TS_PATH.write_text(ts_text, encoding="utf-8")
    return {"schema": SCHEMA_PATH, "typescript": TS_PATH}


def check_contract_artifacts() -> list[str]:
    expected_schema = render_schema_bundle()
    expected_ts = render_typescript()
    mismatches: list[str] = []
    if not SCHEMA_PATH.exists() or SCHEMA_PATH.read_text(encoding="utf-8") != expected_schema:
        mismatches.append(str(SCHEMA_PATH))
    if not TS_PATH.exists() or TS_PATH.read_text(encoding="utf-8") != expected_ts:
        mismatches.append(str(TS_PATH))
    return mismatches


def main(*, check: bool = False) -> int:
    if check:
        mismatches = check_contract_artifacts()
        if mismatches:
            print(json.dumps({"status": "drift", "paths": mismatches}, ensure_ascii=False))
            return 1
        print(json.dumps({"status": "ok"}, ensure_ascii=False))
        return 0
    outputs = write_contract_artifacts()
    print(json.dumps({"status": "written", "outputs": {key: str(path) for key, path in outputs.items()}}, ensure_ascii=False))
    return 0
