// This file is generated by the Anvil contract generator. Do not edit by hand.

export type MemoryLayerId = "session" | "user" | "workspace";

export type SessionSearchScope = "all" | "exclude_current" | "current";

export type SessionSearchMode = "recent" | "search" | "summarize";

export type ErrorResponse = {
  error: string;
  detail?: string | null;
  kind?: string | null;
};

export type HealthView = {
  status?: string;
  phase?: string;
};

export type ShellCommandArgumentView = {
  name: string;
  placeholder: string;
  required?: boolean;
  repeatable?: boolean;
  values: string[];
};

export type ShellCommandView = {
  name: string;
  bare_name: string;
  aliases: string[];
  description: string;
  category: string;
  args_hint?: string;
  action: string;
  scopes: string[];
  keybinding?: string | null;
  stream_output?: boolean;
  stateful?: boolean;
  arguments: ShellCommandArgumentView[];
};

export type ShellCommandCatalogView = {
  commands: ShellCommandView[];
  groups: Record<string, number>;
  default_scope?: string;
  total?: number;
};

export type ThreadCreateRequest = {
  thread_id?: string | null;
  workspace_root?: string | null;
};

export type ThreadView = {
  thread_id: string;
  title?: string | null;
  status: string;
  updated_at: string;
  last_message_at?: string | null;
  last_user_message_preview?: string | null;
  has_pending_approval?: boolean;
  has_active_subagent_tasks?: boolean;
  source_kind?: string | null;
  source_label?: string | null;
  channel_badge?: string | null;
};

export type CompactionDiagnosticsView = {
  compaction_level?: number | null;
  compaction_level_label?: string | null;
  compaction_reason?: string | null;
  summary_source?: string | null;
  summary_model?: string | null;
  summary_error_type?: string | null;
  has_existing_summary?: boolean | null;
  archived_message_count?: number;
  tool_call_count?: number;
  tool_result_count?: number;
  image_block_count?: number;
  truncated_message_count?: number;
  pruned_tool_result_count?: number;
  serialized_chars?: number | null;
  serialized_tokens?: number | null;
  summary_prompt_tokens?: number | null;
  compaction_input_tokens?: number | null;
  compaction_summary_tokens?: number | null;
  compaction_savings_tokens?: number | null;
  keep_recent_turns?: number | null;
};

export type TokenUsageBreakdownView = {
  input_tokens?: number | null;
  output_tokens?: number | null;
  total_tokens?: number | null;
  cache_read_tokens?: number | null;
  cache_write_tokens?: number | null;
  reasoning_tokens?: number | null;
};

export type TokenUsageSummaryView = {
  model?: string | null;
  concrete_model?: string | null;
  provider?: string | null;
  request_count?: number | null;
  input_tokens?: number | null;
  output_tokens?: number | null;
  total_tokens?: number | null;
  cache_read_tokens?: number | null;
  cache_write_tokens?: number | null;
  reasoning_tokens?: number | null;
  total?: TokenUsageBreakdownView | null;
  last?: TokenUsageBreakdownView | null;
  estimated_cost_usd?: number | null;
  cost_status?: string | null;
  currency?: string | null;
  pricing_source?: string | null;
  provider_models: string[];
};

export type ArchivedSummaryView = {
  summary_id: string;
  summary_text: string;
  covers_turn_range: number[];
  token_count: number;
  created_at?: string | null;
  prompt_snapshot_id: string;
  compaction_level?: number;
  compaction_level_label?: string | null;
  compaction_reason?: string | null;
  diagnostics?: CompactionDiagnosticsView | null;
};

export type TodoSnapshotItemView = {
  id: string;
  content: string;
  status?: string;
  created_at?: string | null;
  depends_on: string[];
};

export type ContextWindowUsageView = {
  model?: string | null;
  concrete_model?: string | null;
  provider?: string | null;
  context_tokens?: number | null;
  estimated_context_tokens?: number | null;
  context_source?: string | null;
  context_breakdown: Record<string, number>;
  context_breakdown_percentages: Record<string, number>;
  dominant_context_category?: string | null;
  input_tokens?: number | null;
  output_tokens?: number | null;
  total_tokens?: number | null;
  request_count?: number | null;
  context_window_tokens?: number | null;
  auto_compact_threshold_tokens?: number | null;
  usage_ratio?: number | null;
  compact_ratio?: number | null;
  compact_status?: string;
  summarization_triggered?: boolean;
  compaction_level?: number;
  compaction_level_label?: string | null;
  compaction_reason?: string | null;
  compaction_input_tokens?: number | null;
  compaction_summary_tokens?: number | null;
  compaction_savings_tokens?: number | null;
  compaction_keep_recent_turns?: number | null;
  compaction_diagnostics?: CompactionDiagnosticsView | null;
  estimated_cost_usd?: number | null;
  cost_status?: string | null;
  currency?: string | null;
  message_tokens?: number | null;
  system_tokens?: number | null;
  tool_schema_tokens?: number | null;
  skill_tokens?: number | null;
  memory_tokens?: number | null;
  project_context_tokens?: number | null;
  runtime_path_tokens?: number | null;
  autocompact_buffer_tokens?: number | null;
  free_space_tokens?: number | null;
  cache_read_tokens?: number | null;
  cache_write_tokens?: number | null;
  cache_hit_ratio?: number | null;
  cache_savings_tokens?: number | null;
};

export type PromptCacheDiagnosticsView = {
  hits?: number;
  misses?: number;
  writes?: number;
  evictions?: number;
  bypasses?: number;
  size_before?: number | null;
  size_after?: number | null;
  net_size_change?: number | null;
  max_entries?: number | null;
  cumulative_hits?: number | null;
  cumulative_misses?: number | null;
  cumulative_writes?: number | null;
  cumulative_evictions?: number | null;
  cumulative_bypasses?: number | null;
  cumulative_size?: number | null;
};

export type PromptSectionTokenLedgerView = {
  stable_prompt_tokens?: number | null;
  volatile_prompt_tokens?: number | null;
  stable_section_tokens: Record<string, number>;
  volatile_section_tokens: Record<string, number>;
};

export type ContextCacheDiagnosticsView = {
  project_context_cache_status?: string | null;
  project_context_fingerprint?: string | null;
  project_context_file_count?: number;
  project_context_truncated_file_count?: number;
  project_context_total_chars?: number;
  project_context_discovery_scanned_path_count?: number;
  project_context_discovery_max_scanned_paths?: number;
  project_context_discovery_scan_truncated?: boolean;
  project_context_scope_counts: Record<string, number>;
  project_context_applies_to_counts: Record<string, number>;
  runtime_path_cache_status?: string | null;
  runtime_path_fingerprint?: string | null;
  runtime_path_root_count?: number;
  runtime_path_host_bridge_count?: number;
};

export type CapabilityAssemblyDiagnosticsView = {
  discovered_tool_count?: number;
  enabled_tool_count?: number;
  materialized_tool_count?: number;
  visible_tool_count?: number;
  deferred_tool_count?: number;
  active_promotion_count?: number;
  visible_schema_token_budget?: number | null;
  visible_schema_tokens?: number;
  deferred_schema_tokens?: number;
  total_schema_tokens?: number;
  visible_schema_budget_remaining_tokens?: number | null;
  schema_compacted_tool_count?: number;
  schema_deferred_tool_count?: number;
  action_prefilter_deferred_tool_count?: number;
  sanitizer_truncated_tool_count?: number;
  assembly_stage_durations_ms: Record<string, number>;
  slowest_assembly_stage?: string | null;
  slowest_assembly_stage_duration_ms?: number | null;
  skills_discovery_cache_hit?: boolean | null;
  skills_discovery_watch_enabled?: boolean | null;
  skills_discovery_root_count?: number;
  skills_discovery_manifest_count?: number;
  skills_discovery_enabled_count?: number;
  skills_discovery_package_count?: number;
  skills_discovery_stage_durations_ms: Record<string, number>;
  slowest_skills_discovery_stage?: string | null;
  slowest_skills_discovery_stage_duration_ms?: number | null;
  visible_by_source_kind: Record<string, number>;
  deferred_by_source_kind: Record<string, number>;
  visible_by_group: Record<string, number>;
  deferred_by_group: Record<string, number>;
};

export type MemoryInjectionDiagnosticsView = {
  source?: string;
  status?: string;
  snapshot_id?: string | null;
  query_tokens?: number;
  curated_match_count?: number;
  archive_hit_count?: number;
  evidence_count?: number;
  provider_note_count?: number;
  summary_present?: boolean;
  rendered_tokens_before_truncation?: number;
  rendered_tokens?: number;
  token_budget?: number | null;
  truncated?: boolean;
  error_type?: string | null;
  store_counts: Record<string, number>;
  source_kind_counts: Record<string, number>;
};

export type RuntimePhaseTimingMarkView = {
  phase: string;
  label: string;
  elapsed_ms: number;
  duration_since_previous_ms: number;
};

export type RunEventLogSummaryView = {
  event_count?: number;
  run_count?: number | null;
  last_event_id?: string | null;
  last_sequence?: number | null;
  last_kind?: string | null;
  last_run_id?: string | null;
};

export type RuntimePhaseTimingsView = {
  run_id?: string | null;
  thread_id?: string | null;
  status?: string;
  started_at?: string | null;
  total_elapsed_ms?: number | null;
  runtime_assembly_elapsed_ms?: number | null;
  model_start_wait_ms?: number | null;
  first_model_event_elapsed_ms?: number | null;
  first_content_delta_elapsed_ms?: number | null;
  first_content_wait_ms?: number | null;
  post_content_elapsed_ms?: number | null;
  completed_elapsed_ms?: number | null;
  marks: RuntimePhaseTimingMarkView[];
  event_log?: RunEventLogSummaryView | null;
};

export type RuntimePathRootView = {
  virtual_path: string;
  kind: string;
  description: string;
  writable?: boolean;
  display_root?: string | null;
};

export type ProjectContextFileView = {
  virtual_path: string;
  relative_path: string;
  applies_to: string;
  scope?: string;
  truncated?: boolean;
};

export type ThreadStateView = {
  thread_id: string;
  run_id?: string | null;
  status: string;
  execution_mode?: "chat" | "agent" | "full_access";
  is_plan_mode?: boolean;
  selected_model?: string | null;
  selected_profile?: string | null;
  selected_reasoning_effort?: string | null;
  effective_model?: string | null;
  title?: string | null;
  summary?: string | null;
  todo_snapshot: TodoSnapshotItemView[];
  archived_summaries: ArchivedSummaryView[];
  prompt_snapshot_id?: string | null;
  prompt_snapshot_hash?: string | null;
  project_context_fingerprint?: string | null;
  project_context_files: ProjectContextFileView[];
  active_model?: string | null;
  reasoning_effort?: string | null;
  token_usage: Record<string, unknown>;
  token_usage_summary?: TokenUsageSummaryView | null;
  context_window_usage?: ContextWindowUsageView | null;
  prompt_cache_diagnostics?: PromptCacheDiagnosticsView | null;
  prompt_section_token_ledger?: PromptSectionTokenLedgerView | null;
  context_cache_diagnostics?: ContextCacheDiagnosticsView | null;
  capability_assembly_diagnostics?: CapabilityAssemblyDiagnosticsView | null;
  memory_injection_diagnostics?: MemoryInjectionDiagnosticsView | null;
  compaction_diagnostics?: CompactionDiagnosticsView | null;
  runtime_phase_timings?: RuntimePhaseTimingsView | null;
  last_message_interrupted?: boolean;
  last_message_interrupted_reason?: string | null;
  approval_policy_summary?: string | null;
  allowed_local_actions: string[];
  requires_approval_actions: string[];
  restricted_actions: string[];
  visible_tool_names: string[];
  deferred_tool_names: string[];
  enabled_skill_ids: string[];
  memory_namespace?: string | null;
  injected_memory_snapshot_id?: string | null;
  has_pending_approval?: boolean;
  pending_approval_reason?: string | null;
  pending_user_interaction?: UserInteractionRequestView | null;
  output_artifacts: ArtifactRefView[];
  uploaded_files: ArtifactRefView[];
  presented_artifacts: ArtifactRefView[];
  workspace_mode?: string;
  workspace_root?: string | null;
  resolved_workspace_path?: string | null;
  uploads_path?: string | null;
  outputs_path?: string | null;
  runtime_path_roots: RuntimePathRootView[];
  active_subagent_task_ids: string[];
  subagent_tasks: SubagentTaskView[];
  process_sessions: ProcessSessionView[];
  durable_subagent_job_history: SubagentEventView[];
  tool_calls: ToolCallRecordView[];
  recent_tool_activity: ToolActivityView[];
  recent_approval_events: ApprovalEventView[];
  runtime_operator_status?: RuntimeOperatorStatusView;
  last_error?: string | null;
  runtime_capabilities?: RuntimeCapabilitiesView;
  queued_followups: QueuedFollowUpView[];
  active_followup_dispatch?: QueuedFollowUpDispatchView | null;
};

export type MessageContentBlockView = {
  type: string;
  text?: string;
  url?: string | null;
  mime_type?: string | null;
  name?: string | null;
  artifact_url?: string | null;
  metadata: Record<string, unknown>;
};

export type ReasoningView = {
  text: string;
  block_count?: number;
  duration_ms?: number | null;
};

export type ToolCallView = {
  tool_call_id?: string | null;
  name?: string | null;
  display_name?: string | null;
  source_kind?: string | null;
  source_id?: string | null;
  capability_group?: string | null;
  tool_execution_mode?: string | null;
  args: Record<string, unknown>;
  status?: string | null;
  result_text?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  duration_ms?: number | null;
  input: Record<string, unknown>;
  output?: unknown | null;
  is_error?: boolean;
  visibility?: string;
  sequence?: number | null;
};

export type ToolActivityView = {
  tool_call_id?: string | null;
  message_id?: string | null;
  name?: string | null;
  display_name?: string | null;
  source_kind?: string | null;
  source_id?: string | null;
  capability_group?: string | null;
  tool_execution_mode?: string | null;
  args: Record<string, unknown>;
  status?: string | null;
  result_text?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  duration_ms?: number | null;
};

export type ToolCallRecordView = {
  run_id?: string | null;
  thread_id?: string | null;
  message_id?: string | null;
  block_id?: string | null;
  sequence?: number | null;
  tool_call_id?: string | null;
  name?: string | null;
  display_name?: string | null;
  source_kind?: string | null;
  source_id?: string | null;
  capability_group?: string | null;
  tool_execution_mode?: string | null;
  input: Record<string, unknown>;
  output?: unknown | null;
  status?: string | null;
  is_error?: boolean;
  error_message?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  duration_ms?: number | null;
  visibility?: string;
};

export type RuntimeTimelineItemView = {
  item_id: string;
  kind: string;
  status: string;
  title: string;
  detail?: string | null;
  timestamp?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  duration_ms?: number | null;
  source_id?: string | null;
  source_kind?: string | null;
  hidden?: boolean;
};

export type RuntimeOperatorStatusView = {
  status?: string;
  active_tool_count?: number;
  completed_tool_count?: number;
  failed_tool_count?: number;
  pending_approval_count?: number;
  running_process_count?: number;
  active_subagent_count?: number;
  latest_activity?: string | null;
  latest_activity_at?: string | null;
  runtime_phase_timings?: RuntimePhaseTimingsView | null;
  timeline: RuntimeTimelineItemView[];
};

export type DocumentOutlineEntryView = {
  title?: string | null;
  line?: number | null;
  truncated?: boolean;
};

export type CompanionArtifactView = {
  kind: string;
  label: string;
  artifact_url?: string | null;
  virtual_path?: string | null;
  provider?: string | null;
  internal?: boolean;
  source_scope?: string | null;
};

export type DocumentExtractionView = {
  status: string;
  provider?: string | null;
  ocr_provider?: string | null;
  page_count?: number | null;
  text_layer_present?: boolean | null;
  diagnostics: string[];
};

export type ArtifactRefView = {
  kind: string;
  label: string;
  artifact_url?: string | null;
  virtual_path?: string | null;
  source_scope?: string | null;
  internal?: boolean;
  extension?: string | null;
  markdown_file?: string | null;
  markdown_virtual_path?: string | null;
  markdown_artifact_url?: string | null;
  companions: CompanionArtifactView[];
  extraction?: DocumentExtractionView | null;
  outline: DocumentOutlineEntryView[];
  outline_preview: string[];
  converter_used?: string | null;
  ocr_used?: boolean;
  conversion_error?: string | null;
};

export type ApprovalView = {
  decision: string;
  reason?: string | null;
  action_kind?: string | null;
  request_id?: string | null;
  requested_permissions: string[];
  scope_options: string[];
};

export type ApprovalEventView = {
  request_id?: string | null;
  decision: string;
  reason?: string | null;
  action_kind?: string | null;
  requested_permissions: string[];
  scope_options: string[];
  status: string;
  execution_mode?: string | null;
  created_at: string;
  resolved_at?: string | null;
};

export type UserInteractionOptionView = {
  id: string;
  label: string;
  description?: string | null;
  recommended?: boolean;
  disabled?: boolean;
  metadata: Record<string, unknown>;
};

export type UserInteractionFieldView = {
  field_id: string;
  label: string;
  description?: string | null;
  selection_mode?: "single" | "multiple" | "text";
  options: UserInteractionOptionView[];
  min_selections?: number;
  max_selections?: number | null;
  allow_custom?: boolean;
  custom_label?: string | null;
  placeholder?: string | null;
  required?: boolean;
  metadata: Record<string, unknown>;
};

export type UserInteractionRequestView = {
  request_id: string;
  kind?: string;
  title?: string | null;
  question: string;
  description?: string | null;
  selection_mode?: "single" | "multiple" | "text";
  options: UserInteractionOptionView[];
  min_selections?: number;
  max_selections?: number | null;
  allow_custom?: boolean;
  custom_label?: string | null;
  placeholder?: string | null;
  required?: boolean;
  source_tool_name?: string;
  fields: UserInteractionFieldView[];
};

export type UserInteractionFieldResponseView = {
  field_id: string;
  selected_option_ids: string[];
  custom_response?: string | null;
  free_text?: string | null;
};

export type UserInteractionSubmitRequest = {
  request_id: string;
  selected_option_ids?: string[];
  custom_response?: string | null;
  free_text?: string | null;
  field_responses?: UserInteractionFieldResponseView[];
};

export type MessageStepView = {
  step_id: string;
  message_id: string;
  type: string;
  title: string;
  action?: string | null;
  status: string;
  duration?: string | null;
  duration_ms?: number | null;
  payload?: string;
  language?: string;
  tool_name?: string | null;
  tool_call_id?: string | null;
  order?: number;
  started_at?: string | null;
  completed_at?: string | null;
  error?: string | null;
  metadata: Record<string, unknown>;
  visibility?: string;
  block_id?: string | null;
  sequence?: number | null;
};

export type MessageView = {
  message_id: string;
  client_message_id?: string | null;
  role: string;
  content: string;
  steps: MessageStepView[];
  content_blocks: MessageContentBlockView[];
  reasoning?: ReasoningView | null;
  tool_calls: ToolCallView[];
  tool_call_id?: string | null;
  name?: string | null;
  status?: string | null;
  stream_status?: string | null;
  artifact_refs: ArtifactRefView[];
  approval?: ApprovalView | null;
};

export type MessageWindowView = {
  total?: number;
  offset?: number;
  limit?: number | null;
  returned?: number;
  has_more_before?: boolean;
  has_more_after?: boolean;
  truncated?: boolean;
  start_message_id?: string | null;
  end_message_id?: string | null;
};

export type StreamCapabilitiesView = {
  supports_step_chain?: boolean;
  supports_message_delta?: boolean;
  supports_reasoning_delta?: boolean;
  supports_structured_events?: boolean;
};

export type RuntimeCapabilitiesView = {
  summarization_enabled?: boolean;
  plan_mode_enabled?: boolean;
  view_image_enabled?: boolean;
  memory_enabled?: boolean;
  skills_count?: number;
  mcp_servers_connected?: number;
  sandbox_mode?: string;
  supported_sandbox_modes: string[];
  isolated_sandbox_supported?: boolean;
  guardrails_enabled?: boolean;
};

export type ThreadDetailView = {
  thread: ThreadView;
  state: ThreadStateView;
  messages: MessageView[];
  message_window?: MessageWindowView;
  pending_approval?: ApprovalView | null;
  pending_user_interaction?: UserInteractionRequestView | null;
  stream_capabilities?: StreamCapabilitiesView;
};

export type ThreadSettingsView = {
  thread_id: string;
  execution_mode: "chat" | "agent" | "full_access";
  selected_model?: string | null;
  selected_profile?: string | null;
  selected_reasoning_effort?: string | null;
  is_plan_mode?: boolean;
  workspace_root?: string | null;
  workspace_mode?: string;
  anvil_home?: string | null;
  anvil_profile?: string | null;
  anvil_profile_home?: string | null;
  resolved_workspace_path?: string | null;
  runtime_path_roots: RuntimePathRootView[];
};

export type ThreadSettingsUpdateRequest = {
  execution_mode?: "chat" | "agent" | "full_access" | null;
  selected_model?: string | null;
  selected_profile?: string | null;
  selected_reasoning_effort?: string | null;
  is_plan_mode?: boolean | null;
  workspace_root?: string | null;
};

export type TrajectoryCompressionRequest = {
  enabled?: boolean | null;
  max_turns?: number | null;
  keep_first_turns?: number | null;
  keep_last_turns?: number | null;
  max_message_chars?: number | null;
  max_tool_result_chars?: number | null;
  max_metadata_chars?: number | null;
};

export type TrajectoryExportRequest = {
  format?: string | null;
  include_system?: boolean | null;
  include_tools?: boolean | null;
  include_tool_args?: boolean | null;
  include_metadata?: boolean | null;
  include_reasoning?: boolean | null;
  include_parsed_tool_calls?: boolean | null;
  include_hidden_steps?: boolean | null;
  include_artifacts?: boolean | null;
  include_approvals?: boolean | null;
  include_token_usage?: boolean | null;
  scrub_secrets?: boolean | null;
  compression?: TrajectoryCompressionRequest | null;
};

export type TrajectoryBatchExportRequest = {
  thread_ids?: string[];
  output_path?: string | null;
  write_jsonl?: boolean | null;
  include_entries?: boolean | null;
  learn_procedures?: boolean;
  min_quality_status?: string | null;
  options?: TrajectoryExportRequest | null;
};

export type TrajectoryTurnView = {
  from_: string;
  value: string;
  message_id?: string | null;
  role?: string | null;
  metadata: Record<string, unknown>;
};

export type ToolUsageStatsView = {
  count?: number;
  success_count?: number;
  error_count?: number;
  running_count?: number;
  total_duration_ms?: number;
};

export type TrajectoryStatsView = {
  message_count?: number;
  exported_turn_count?: number;
  original_turn_count?: number;
  omitted_turn_count?: number;
  user_turns?: number;
  assistant_turns?: number;
  system_turns?: number;
  tool_turns?: number;
  tool_call_count?: number;
  tool_success_count?: number;
  tool_error_count?: number;
  approval_count?: number;
  artifact_count?: number;
  completed?: boolean;
  interrupted?: boolean;
  token_usage: Record<string, unknown>;
  tool_stats: Record<string, ToolUsageStatsView>;
};

export type TrajectoryQualityIssueView = {
  severity: string;
  code: string;
  message: string;
  turn_index?: number | null;
  message_id?: string | null;
  tool_name?: string | null;
};

export type TrajectoryQualityReportView = {
  status?: string;
  score?: number;
  issues: TrajectoryQualityIssueView[];
  summary: Record<string, unknown>;
};

export type TrajectoryExportView = {
  id: string;
  thread_id: string;
  run_id?: string | null;
  timestamp: string;
  model?: string | null;
  completed?: boolean;
  conversations: TrajectoryTurnView[];
  stats?: TrajectoryStatsView;
  quality?: TrajectoryQualityReportView;
  metadata: Record<string, unknown>;
  format?: string;
};

export type TrajectoryBatchManifestView = {
  dataset_id: string;
  format?: string;
  jsonl_path?: string | null;
  manifest_path?: string | null;
  exported_count?: number;
  skipped_count?: number;
  thread_ids: string[];
  diagnostics: string[];
  stats: Record<string, unknown>;
  created_at: string;
};

export type TrajectoryBatchExportView = {
  exported_count: number;
  skipped_count?: number;
  path?: string | null;
  format?: string;
  entries: TrajectoryExportView[];
  diagnostics: string[];
  manifest: TrajectoryBatchManifestView;
};

export type EvaluationReportOptionsView = {
  include_conversation_preview?: boolean | null;
  max_preview_chars?: number | null;
  max_tool_result_chars?: number | null;
  scrub_secrets?: boolean | null;
  include_markdown?: boolean | null;
};

export type EvaluationReportRequestView = {
  thread_ids: string[];
  options?: EvaluationReportOptionsView | null;
  evaluator_results: Record<string, EvaluationReportEvaluatorResultView>;
  write_markdown?: boolean;
  output_path?: string | null;
};

export type EvaluationReportEvaluatorResultView = {
  evaluator?: string;
  score?: number | null;
  passed?: boolean | null;
  max_score?: number | null;
  task_id?: string | null;
  run_id?: string | null;
  duration_ms?: number | null;
  summary?: string | null;
  details: Record<string, unknown>;
};

export type EvaluationReportRuntimeSectionView = {
  status: string;
  model?: string | null;
  execution_mode?: string | null;
  reasoning_effort?: string | null;
  runtime_phase_timings: Record<string, unknown>;
  runtime_phase_diagnostics: Record<string, unknown>;
  runtime_assembly_snapshot: Record<string, unknown>;
  runtime_assembly_diff: Record<string, unknown>;
  context_window_usage: Record<string, unknown>;
  token_usage: Record<string, unknown>;
  model_fallback_history: Record<string, unknown>[];
};

export type EvaluationReportToolCallView = {
  tool_call_id?: string | null;
  message_id?: string | null;
  name?: string | null;
  display_name?: string | null;
  capability_group?: string | null;
  status?: string | null;
  duration_ms?: number | null;
  result_text?: string | null;
};

export type EvaluationReportStepView = {
  step_id: string;
  message_id?: string | null;
  type: string;
  title?: string | null;
  status?: string | null;
  visibility?: string | null;
  tool_name?: string | null;
  tool_call_id?: string | null;
  duration_ms?: number | null;
  order?: number | null;
  started_at?: string | null;
  completed_at?: string | null;
  payload_preview?: string | null;
  action_preview?: string | null;
  error_preview?: string | null;
};

export type EvaluationReportStepChainSectionView = {
  total?: number;
  returned?: number;
  truncated?: boolean;
  visible_step_count?: number;
  hidden_step_count?: number;
  open_step_count?: number;
  error_step_count?: number;
  type_counts: Record<string, number>;
  status_counts: Record<string, number>;
  visibility_counts: Record<string, number>;
  items: EvaluationReportStepView[];
};

export type EvaluationReportMemorySectionView = {
  namespace?: string | null;
  injected_memory_snapshot_id?: string | null;
  procedure_learning_runs: string[];
  procedure_learning_signatures: string[];
};

export type EvaluationReportCapabilitySectionView = {
  visible_tool_names: string[];
  deferred_tool_names: string[];
  enabled_skill_ids: string[];
  capability_bundle_fingerprint?: string | null;
};

export type EvaluationReportIssueView = {
  severity: string;
  code: string;
  message: string;
};

export type EvaluationThreadReportView = {
  report_id: string;
  thread_id: string;
  run_id?: string | null;
  generated_at: string;
  title?: string | null;
  task_preview?: string | null;
  final_answer_preview?: string | null;
  outcome: string;
  score: number;
  evaluator?: EvaluationReportEvaluatorResultView | null;
  runtime: EvaluationReportRuntimeSectionView;
  trajectory_quality?: TrajectoryQualityReportView;
  stats?: TrajectoryStatsView;
  tool_calls: EvaluationReportToolCallView[];
  step_chain?: EvaluationReportStepChainSectionView;
  memory?: EvaluationReportMemorySectionView;
  capabilities?: EvaluationReportCapabilitySectionView;
  approvals: Record<string, unknown>[];
  artifacts: Record<string, unknown>;
  hidden_bug_risks: EvaluationReportIssueView[];
  recommendations: string[];
  notes: string[];
  markdown?: string | null;
};

export type EvaluationBatchReportView = {
  report_id: string;
  generated_at: string;
  thread_reports: EvaluationThreadReportView[];
  missing_thread_ids: string[];
  score?: number;
  markdown_path?: string | null;
  summary: Record<string, unknown>;
  markdown?: string | null;
};

export type RunRequestBody = {
  message: string;
  client_message_id?: string | null;
  execution_mode?: "chat" | "agent" | "full_access";
  selected_model?: string | null;
  selected_reasoning_effort?: string | null;
  profile?: string | null;
  request_context?: string | null;
  approval_context?: string | null;
  upload_context?: string | null;
  uploaded_filenames?: string[];
  promoted_capabilities?: string[];
  is_plan_mode?: boolean | null;
  followup_dispatch_id?: string | null;
};

export type QueuedFollowUpCreateRequest = {
  message: string;
  mode?: "followup" | "guidance";
  insert_position?: "front" | "back";
  execution_mode?: "chat" | "agent" | "full_access" | null;
  selected_model?: string | null;
  selected_reasoning_effort?: string | null;
  profile?: string | null;
  upload_context?: string | null;
  uploaded_filenames?: string[];
  uploaded_file_refs?: ArtifactRefView[];
  promoted_capabilities?: string[];
  is_plan_mode?: boolean | null;
};

export type QueuedFollowUpUpdateRequest = {
  message?: string | null;
  mode?: "followup" | "guidance" | null;
};

export type QueuedFollowUpView = {
  queue_id: string;
  thread_id: string;
  message: string;
  mode?: "followup" | "guidance";
  status?: string;
  created_at: string;
  updated_at: string;
  execution_mode?: "chat" | "agent" | "full_access" | null;
  selected_model?: string | null;
  selected_reasoning_effort?: string | null;
  profile?: string | null;
  upload_context?: string | null;
  uploaded_filenames: string[];
  uploaded_file_refs: ArtifactRefView[];
  promoted_capabilities: string[];
  is_plan_mode?: boolean | null;
  dispatch_id?: string | null;
};

export type QueuedFollowUpDispatchView = {
  dispatch_id: string;
  queue_id: string;
  started_at: string;
  status?: "dispatching";
};

export type MessageEditResendRequest = {
  message: string;
  execution_mode?: "chat" | "agent" | "full_access" | null;
  selected_model?: string | null;
  selected_reasoning_effort?: string | null;
  profile?: string | null;
  request_context?: string | null;
  approval_context?: string | null;
  upload_context?: string | null;
  promoted_capabilities?: string[];
  is_plan_mode?: boolean | null;
};

export type ApprovalResumeRequest = {
  approval_context?: string;
  selected_model?: string | null;
  selected_reasoning_effort?: string | null;
  profile?: string | null;
  request_context?: string | null;
  upload_context?: string | null;
  promoted_capabilities?: string[];
  is_plan_mode?: boolean | null;
};

export type UserInteractionResumeRequest = {
  request_id: string;
  selected_option_ids?: string[];
  custom_response?: string | null;
  free_text?: string | null;
  field_responses?: UserInteractionFieldResponseView[];
  selected_model?: string | null;
  selected_reasoning_effort?: string | null;
  profile?: string | null;
  request_context?: string | null;
  upload_context?: string | null;
  promoted_capabilities?: string[];
  is_plan_mode?: boolean | null;
};

export type ApprovalCancelRequest = {
  reason?: string;
};

export type ThreadDeleteView = {
  thread_id: string;
  deleted?: boolean;
};

export type RunAcceptedView = {
  thread_id: string;
  status: string;
};

export type RunCompletedView = {
  thread_id: string;
  status: string;
  assistant_message?: string | null;
  last_error?: string | null;
  thread: ThreadView;
  state: ThreadStateView;
};

export type RunStreamEvent = {
  event: string;
  data: Record<string, unknown>;
  event_id?: string | null;
  sequence?: number | null;
  message_id?: string | null;
  block_id?: string | null;
  visibility?: string | null;
  source?: string | null;
};

export type RunEventReplayView = {
  thread_id: string;
  run_id?: string | null;
  after_sequence?: number | null;
  next_cursor: number;
  has_more?: boolean;
  events: RunStreamEvent[];
};

export type SystemEventView = {
  event: string;
  system_version?: number | null;
  data: Record<string, unknown>;
};

export type UploadItemView = {
  filename: string;
  kind: string;
  virtual_path: string;
  artifact_url: string;
  source_scope?: string | null;
  internal?: boolean;
  extension?: string | null;
  markdown_file?: string | null;
  markdown_virtual_path?: string | null;
  markdown_artifact_url?: string | null;
  companions: CompanionArtifactView[];
  extraction?: DocumentExtractionView | null;
  outline: DocumentOutlineEntryView[];
  outline_preview: string[];
  converter_used?: string | null;
  ocr_used?: boolean;
  conversion_error?: string | null;
};

export type UploadResult = {
  thread_id: string;
  files: UploadItemView[];
};

export type ModelView = {
  name: string;
  display_name?: string | null;
  description?: string | null;
  available?: boolean;
  source?: string | null;
  use?: string | null;
  provider: string;
  provider_kind?: string | null;
  model_name?: string | null;
  default_model?: string | null;
  selected_model?: string | null;
  model_catalog: string[];
  context_window_tokens?: number | null;
  auto_compact_threshold_tokens?: number | null;
  max_tokens?: number | null;
  temperature?: number | null;
  top_p?: number | null;
  model_context_windows: Record<string, number>;
  model_auto_compact_thresholds: Record<string, number>;
  base_url?: string | null;
  api_key_env?: string | null;
  default_reasoning_effort?: string | null;
  supports_tool_calling?: boolean;
  supports_thinking?: boolean;
  supports_reasoning_effort?: boolean;
  supports_vision?: boolean;
  supports_image_generation?: boolean;
  timeout?: number | null;
  request_timeout?: number | null;
  default_request_timeout?: number | null;
  max_retries?: number | null;
  use_responses_api?: boolean | null;
  output_version?: string | null;
  image_generation?: Record<string, unknown> | null;
  diagnostics: string[];
  capabilities: Record<string, unknown>;
  internal_task_default?: boolean;
  internal_task_selected_model?: string | null;
  internal_task_available?: boolean | null;
  internal_task_health?: string | null;
  internal_task_health_checked_at?: string | null;
  internal_task_health_message?: string | null;
};

export type ModelSelectionUpdateRequest = {
  model_name: string;
  default_reasoning_effort?: string | null;
  internal_task_default?: boolean | null;
};

export type ModelSelectionUpdateView = {
  name: string;
  selected_model: string;
  default_reasoning_effort?: string | null;
  internal_task_default?: boolean;
  config_path: string;
  config_fingerprint: string;
  model: ModelView;
};

export type ModelHealthCheckRequest = {
  model_name?: string | null;
  subsystem?: string;
};

export type ModelHealthCheckView = {
  name: string;
  model_name: string;
  subsystem: string;
  ok: boolean;
  status: string;
  message?: string | null;
  checked_at: string;
  latency_ms?: number | null;
  config_fingerprint: string;
};

export type ModelProviderPresetView = {
  provider: string;
  display_name: string;
  description?: string | null;
  base_url?: string | null;
  api_key_env: string;
  provider_kind?: string | null;
  use?: string | null;
  model_catalog: string[];
  default_model?: string | null;
  context_window_tokens?: number | null;
  auto_compact_threshold_tokens?: number | null;
  default_reasoning_effort?: string | null;
  supports_tool_calling?: boolean;
  supports_thinking?: boolean;
  supports_reasoning_effort?: boolean;
  supports_vision?: boolean;
  supports_image_generation?: boolean;
  defaults: Record<string, unknown>;
};

export type ModelProviderUpsertRequest = {
  provider: string;
  name?: string | null;
  display_name?: string | null;
  description?: string | null;
  base_url?: string | null;
  api_key?: string | null;
  api_key_env?: string | null;
  models?: string[];
  default_model?: string | null;
  default_reasoning_effort?: string | null;
  context_window_tokens?: number | null;
  auto_compact_threshold_tokens?: number | null;
  max_tokens?: number | null;
  temperature?: number | null;
  top_p?: number | null;
  timeout?: number | null;
  request_timeout?: number | null;
  default_request_timeout?: number | null;
  max_retries?: number | null;
  use_responses_api?: boolean | null;
  output_version?: string | null;
  default_headers?: Record<string, string> | null;
  extra_body?: Record<string, unknown> | null;
  provider_settings?: Record<string, unknown> | null;
  when_thinking_enabled?: Record<string, unknown> | null;
  when_thinking_disabled?: Record<string, unknown> | null;
  thinking?: Record<string, unknown> | null;
  image_generation?: Record<string, unknown> | null;
  supports_tool_calling?: boolean | null;
  supports_thinking?: boolean | null;
  supports_reasoning_effort?: boolean | null;
  supports_vision?: boolean | null;
  supports_image_generation?: boolean | null;
  extra_fields?: Record<string, unknown>;
};

export type ModelProviderUpsertView = {
  name: string;
  provider: string;
  config_path: string;
  dotenv_path?: string | null;
  config_fingerprint: string;
  model: ModelView;
};

export type ModelProviderDeleteView = {
  name: string;
  deleted: boolean;
  config_path: string;
  config_fingerprint: string;
};

export type ConfigOverviewMetricView = {
  total?: number;
  enabled?: number | null;
  ready?: number | null;
  available?: number | null;
  disabled?: number | null;
  issue_count?: number | null;
  quality_score?: number | null;
  status?: string | null;
  source_counts: Record<string, number>;
  enabled_source_counts: Record<string, number>;
};

export type ConfigOverviewView = {
  status?: string;
  config_fingerprint: string;
  models?: ConfigOverviewMetricView;
  tools?: ConfigOverviewMetricView;
  skills?: ConfigOverviewMetricView;
  memory?: ConfigOverviewMetricView;
  mcp?: ConfigOverviewMetricView;
  plugins?: ConfigOverviewMetricView;
  scheduled?: ConfigOverviewMetricView;
};

export type SkillValidationIssueView = {
  severity: string;
  code: string;
  message: string;
  skill_id?: string | null;
  source_root?: string | null;
  path?: string | null;
  field?: string | null;
};

export type SkillFileEntryView = {
  path: string;
  kind: string;
  size_bytes: number;
  is_binary?: boolean;
};

export type SkillView = {
  skill_id: string;
  title: string;
  summary: string;
  name?: string | null;
  description?: string | null;
  version?: string | null;
  trust?: string | null;
  allowed_tools: string[];
  tags: string[];
  dependencies: Record<string, unknown>[];
  readiness: Record<string, unknown>;
  config: Record<string, unknown>;
  platforms: string[];
  related_skills: string[];
  asset_paths: string[];
  template_paths: string[];
  script_paths: string[];
  reference_paths: string[];
  file_index_scanned_path_count?: number;
  file_index_max_scanned_paths?: number;
  file_index_scan_truncated?: boolean;
  package?: Record<string, unknown> | null;
  enabled?: boolean;
  valid?: boolean;
  issues: SkillValidationIssueView[];
  issue_counts: Record<string, number>;
  body_preview?: string;
  path: string;
  source_root?: string | null;
  source_scope?: string | null;
  read_only?: boolean;
  can_uninstall?: boolean;
};

export type SkillListItemView = {
  skill_id: string;
  title: string;
  summary: string;
  allowed_tools: string[];
  tags: string[];
  enabled?: boolean;
  valid?: boolean;
  issue_counts: Record<string, number>;
  body_preview?: string;
  source_scope?: string | null;
  trust?: string | null;
  version?: string | null;
  read_only?: boolean;
  can_uninstall?: boolean;
};

export type SkillManageRequest = {
  action: string;
  skill_id?: string | null;
};

export type SkillCuratorRequest = {
  action?: string;
  skill_id?: string | null;
  title?: string | null;
  summary?: string | null;
  body?: string | null;
  rationale?: string | null;
  tags?: string[];
  allowed_tools?: string[];
  file_path?: string | null;
  content?: string | null;
  old_text?: string | null;
  new_text?: string | null;
  absorbed_into?: string | null;
  revision?: string | null;
  outcome?: string | null;
  feedback_source?: string | null;
  confidence?: number | null;
  trigger?: string | null;
  steps?: string[];
  expected_outcome?: string | null;
  evidence_refs?: string[];
  source_ref?: string | null;
  procedure_id?: string | null;
  dry_run?: boolean;
  force?: boolean;
};

export type SkillCuratorAutomationRequest = {
  force_run?: boolean;
};

export type SkillCuratorAutomationStatusResponse = {
  enabled?: boolean;
  last_run_at?: string | null;
  last_status?: string | null;
  last_reason?: string | null;
  last_run_id?: string | null;
  last_counts: Record<string, unknown>;
  last_recommendation_count?: number;
  last_recommendations: Record<string, unknown>[];
  next_run_at?: string | null;
  schedule?: string;
  auto_merge?: boolean;
  pin_protection?: boolean;
  interval_seconds?: number;
  tick_seconds?: number;
  min_idle_hours?: number;
  dry_run?: boolean;
  force?: boolean;
};

export type SkillCuratorAutomationRunResponse = {
  ran?: boolean;
  reason?: string;
  next_run_at?: string | null;
  report?: Record<string, unknown> | null;
};

export type SkillCuratorMaintenanceRequest = {
  dry_run?: boolean;
  force?: boolean;
  source?: string;
};

export type SkillContentView = {
  skill_id: string;
  title: string;
  path: string;
  source_root: string;
  body: string;
  body_preview?: string;
  file_count?: number;
};

export type SkillFileIndexView = {
  skill_id: string;
  path: string;
  source_root: string;
  files: SkillFileEntryView[];
  scanned_path_count?: number;
  max_scanned_paths?: number;
  scan_truncated?: boolean;
};

export type SkillFileReadRequest = {
  relative_path: string;
  max_bytes?: number;
};

export type SkillFileReadView = {
  skill_id: string;
  relative_path: string;
  path: string;
  source_root: string;
  kind: string;
  is_binary?: boolean;
  encoding?: string;
  content?: string;
  truncated?: boolean;
  size_bytes?: number;
};

export type MemoryStoreView = {
  store_id: string;
  display_name: string;
  max_chars: number;
  injection_chars: number;
  max_tokens?: number | null;
  injection_tokens?: number | null;
  effective_max_tokens: number;
  effective_injection_tokens: number;
  budget_source?: string;
  actual_injection_tokens?: number;
  actual_injection_chars?: number;
  usage_chars: number;
  usage_tokens?: number;
  entry_count: number;
  summary: string;
  summary_sections: Record<string, Record<string, string>>;
  snapshot_status?: string;
  updated_at: string;
};

export type MemoryLayerView = {
  layer_id: MemoryLayerId;
  display_name: string;
  description: string;
  writable: boolean;
  entry_count?: number;
  store_id?: string | null;
  summary?: string | null;
};

export type MemoryEntryView = {
  entry_id: string;
  memory_id?: string | null;
  store_id: string;
  layer_id?: string | null;
  content: string;
  category: string;
  source_kind: string;
  priority: number;
  confidence?: number;
  salience?: number;
  last_accessed_at?: string | null;
  evidence_refs: string[];
  supersedes: string[];
  conflicts_with: string[];
  expires_at?: string | null;
  effective_score?: number;
  status?: string;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
};

export type MemoryEntryCreateRequest = {
  content: string;
  category?: string;
  source_kind?: string;
  priority?: number;
  confidence?: number;
  salience?: number;
  evidence_refs?: string[];
};

export type MemoryEntryUpdateRequest = {
  content?: string | null;
  category?: string | null;
  priority?: number | null;
  confidence?: number | null;
  salience?: number | null;
  status?: string | null;
};

export type MemoryProviderView = {
  provider_id: string;
  display_name: string;
  kind?: string;
  origin?: string;
  family: string;
  description: string;
  active: boolean;
  configured: boolean;
  available: boolean;
  supports_prefetch: boolean;
  supports_sync: boolean;
  supports_index?: boolean;
  supports_reflection: boolean;
  supports_explain?: boolean;
  supports_archive_search: boolean;
  roles: string[];
  health?: string;
  diagnostics: string[];
  last_sync_at?: string | null;
};

export type MemoryProviderTestResponse = {
  provider_id: string;
  ok: boolean;
  health?: string;
  diagnostics: string[];
};

export type MemoryArchiveSearchRequest = {
  query: string;
  limit?: number;
};

export type SessionSearchRequest = {
  query?: string;
  thread_id?: string | null;
  limit?: number;
  scope?: SessionSearchScope;
  mode?: SessionSearchMode;
};

export type MemoryArchiveSearchHitView = {
  archive_id: string;
  thread_id: string;
  score: number;
  excerpt: string;
  created_at: string;
};

export type MemoryArchiveSearchResultView = {
  query: string;
  hits: MemoryArchiveSearchHitView[];
  provider_notes: string[];
};

export type PromptSnapshotMetadataView = {
  snapshot_id: string;
  prompt_hash: string;
  skills_fingerprint?: string | null;
  memory_fingerprint?: string | null;
  config_fingerprint: string;
  created_at: string;
};

export type SessionTurnView = {
  archive_id: string;
  thread_id: string;
  user_content: string;
  assistant_content: string;
  status: string;
  created_at: string;
};

export type SessionMemoryView = {
  layer_id?: MemoryLayerId;
  thread_id: string;
  memory_namespace?: string | null;
  injected_memory_snapshot_id?: string | null;
  archive_turn_count?: number;
  recent_turns: SessionTurnView[];
  latest_prompt_snapshot?: PromptSnapshotMetadataView | null;
  session_summary?: string;
};

export type RecallEvidenceView = {
  evidence_id: string;
  source_kind: string;
  source_id: string;
  layer_id?: string | null;
  memory_id?: string | null;
  archive_id?: string | null;
  thread_id?: string | null;
  score?: number;
  match_score?: number | null;
  rerank_score?: number | null;
  recency_score?: number | null;
  final_score?: number | null;
  dropped_reason?: string | null;
  reason?: string;
  excerpt?: string;
};

export type SessionSearchThreadGroupView = {
  thread_id: string;
  hit_count?: number;
  summary?: string;
  excerpts: string[];
  latest_created_at?: string | null;
  hits: MemoryArchiveSearchHitView[];
  evidence: RecallEvidenceView[];
  latest_prompt_snapshot?: PromptSnapshotMetadataView | null;
};

export type SessionSearchResultView = {
  query: string;
  thread_id?: string | null;
  scope: SessionSearchScope;
  groups: SessionSearchThreadGroupView[];
  provider_notes: string[];
  current_thread_snapshot?: PromptSnapshotMetadataView | null;
};

export type MemoryOverviewView = {
  active_provider_id?: string | null;
  runtime_mode?: string;
  legacy_capture_enabled?: boolean;
  migration_status: Record<string, unknown>;
  store_count: number;
  archive_turn_count: number;
  reflection_job_count: number;
  stores: MemoryStoreView[];
  layers: MemoryLayerView[];
};

export type MemoryTraceRequest = {
  thread_id?: string | null;
  target_id?: string | null;
  limit?: number;
};

export type MemoryTraceView = {
  trace_id: string;
  thread_id?: string | null;
  query?: string | null;
  trace_kind: string;
  target_id?: string | null;
  provider_notes: string[];
  evidence: RecallEvidenceView[];
  created_at: string;
};

export type MemoryTraceResponse = {
  items: MemoryTraceView[];
};

export type MemoryRecallBenchmarkCaseView = {
  case_id: string;
  query: string;
  thread_id?: string;
  expected_terms: string[];
  expected_memory_ids: string[];
  expected_archive_thread_ids: string[];
  forbidden_terms: string[];
  forbidden_memory_ids: string[];
  min_score?: number;
};

export type MemoryRecallBenchmarkRequest = {
  suite_id?: string;
  cases?: MemoryRecallBenchmarkCaseView[];
  evidence_limit?: number;
};

export type MemoryRecallBenchmarkCaseResultView = {
  case_id: string;
  query: string;
  passed: boolean;
  score?: number;
  recall_hits?: number;
  expected_count?: number;
  false_positive_count?: number;
  evidence_count?: number;
  top_evidence: RecallEvidenceView[];
  missing_expectations: string[];
  false_positives: string[];
  summary?: string;
};

export type MemoryRecallBenchmarkResponse = {
  suite_id?: string;
  passed?: boolean;
  score?: number;
  case_count?: number;
  passed_count?: number;
  failed_count?: number;
  recall_hit_rate?: number;
  false_positive_rate?: number;
  average_evidence_count?: number;
  cases: MemoryRecallBenchmarkCaseResultView[];
  recommendations: string[];
  generated_at: string;
};

export type MemoryRecallBenchmarkSuiteView = {
  suite_id: string;
  name?: string;
  description?: string;
  cases: MemoryRecallBenchmarkCaseView[];
  tags: string[];
  enabled?: boolean;
  source?: string;
  created_at: string;
  updated_at: string;
  latest_run_id?: string | null;
  latest_score?: number | null;
  latest_passed?: boolean | null;
  latest_run_at?: string | null;
};

export type MemoryRecallBenchmarkSuiteUpsertRequest = {
  suite_id: string;
  name?: string;
  description?: string;
  cases?: MemoryRecallBenchmarkCaseView[];
  tags?: string[];
  enabled?: boolean;
  source?: string;
};

export type MemoryRecallBenchmarkSuiteListResponse = {
  items: MemoryRecallBenchmarkSuiteView[];
};

export type MemoryRecallBenchmarkRunRequest = {
  evidence_limit?: number;
  source?: string;
  record?: boolean;
};

export type MemoryRecallBenchmarkRunView = {
  run_id: string;
  suite_id: string;
  suite_name?: string;
  source?: string;
  report: MemoryRecallBenchmarkResponse;
  created_at: string;
};

export type MemoryRecallBenchmarkRunListResponse = {
  items: MemoryRecallBenchmarkRunView[];
};

export type MemoryConflictView = {
  conflict_id: string;
  memory_id: string;
  conflicting_memory_id: string;
  reason: string;
  created_at: string;
  resolved?: boolean;
  recommended_action?: string | null;
  memory_content?: string | null;
  conflicting_content?: string | null;
};

export type MemoryConflictResponse = {
  items: MemoryConflictView[];
};

export type MemoryStalenessEntryView = {
  memory_id: string;
  layer_id: string;
  stale_score: number;
  reason: string;
  last_accessed_at?: string | null;
  expires_at?: string | null;
  retention_score?: number;
  tier?: string;
  access_count?: number;
  reinforcement_boost?: number;
  temporal_decay?: number;
  salience?: number;
};

export type MemoryStalenessResponse = {
  items: MemoryStalenessEntryView[];
};

export type MemoryRetentionEntryView = {
  memory_id: string;
  store_id: string;
  layer_id?: string | null;
  tier?: string;
  retention_score?: number;
  salience?: number;
  temporal_decay?: number;
  reinforcement_boost?: number;
  access_count?: number;
  last_accessed_at?: string | null;
  created_at: string;
  status?: string;
};

export type MemoryQualityIssueView = {
  issue_id: string;
  severity?: string;
  kind: string;
  store_id?: string | null;
  layer_id?: string | null;
  memory_id?: string | null;
  related_memory_ids: string[];
  message: string;
  recommendation?: string | null;
  score?: number;
};

export type MemoryStoreHealthView = {
  store_id: string;
  layer_id?: string | null;
  status?: string;
  entry_count?: number;
  active_count?: number;
  inactive_count?: number;
  low_confidence_count?: number;
  low_salience_count?: number;
  missing_evidence_count?: number;
  duplicate_cluster_count?: number;
  conflict_count?: number;
  stale_count?: number;
  accessed_count?: number;
  hot_count?: number;
  warm_count?: number;
  cold_count?: number;
  retention_average?: number;
  injection_token_pressure?: number;
  quality_score?: number;
  issues: MemoryQualityIssueView[];
};

export type MemoryHealthResponse = {
  status?: string;
  quality_score?: number;
  archive_turn_count?: number;
  pending_review_count?: number;
  conflict_count?: number;
  stale_count?: number;
  provider_count?: number;
  provider_health: Record<string, string>;
  stores: MemoryStoreHealthView[];
  issues: MemoryQualityIssueView[];
  recommendations: string[];
  generated_at: string;
};

export type MemoryReviewItemView = {
  review_id: string;
  layer_id: string;
  store_id: string;
  action: string;
  content: string;
  category: string;
  priority: number;
  confidence: number;
  salience: number;
  evidence_refs: string[];
  supersedes: string[];
  conflicts_with: string[];
  rationale?: string | null;
  status: string;
  created_at: string;
  updated_at: string;
};

export type MemoryReviewResponse = {
  items: MemoryReviewItemView[];
};

export type MemoryGovernanceActionRequest = {
  action: string;
  reason?: string | null;
  source?: string;
};

export type MemoryGovernanceActionResponse = {
  action: string;
  memory_id: string;
  store_id?: string | null;
  entry_id?: string | null;
  status?: string;
  message?: string;
  entry?: MemoryEntryView | null;
  review_item?: MemoryReviewItemView | null;
  before_retention?: MemoryRetentionEntryView | null;
  after_retention?: MemoryRetentionEntryView | null;
};

export type MemoryGovernancePlanItemView = {
  memory_id: string;
  store_id: string;
  entry_id: string;
  layer_id?: string | null;
  action: string;
  reason: string;
  tier?: string;
  stale_score?: number;
  retention_score?: number;
  salience?: number;
  access_count?: number;
  last_accessed_at?: string | null;
  expires_at?: string | null;
};

export type MemoryGovernanceBatchRequest = {
  policy?: string;
  layer_id?: string | null;
  limit?: number;
  dry_run?: boolean;
  source?: string;
};

export type MemoryGovernanceBatchResponse = {
  policy?: string;
  layer_id?: string | null;
  dry_run?: boolean;
  candidate_count?: number;
  executed_count?: number;
  skipped_count?: number;
  items: MemoryGovernancePlanItemView[];
  results: MemoryGovernanceActionResponse[];
  errors: string[];
};

export type ProfileFacetView = {
  facet_id: string;
  source_memory_id: string;
  entry_id: string;
  store_id?: string;
  class_id: string;
  key: string;
  value: string;
  source_category: string;
  evidence_refs: string[];
  confidence?: number;
  salience?: number;
  priority?: number;
  stability_score?: number;
  state: string;
  user_state: string;
  prompt_visible?: boolean;
  source_polluted?: boolean;
  pollution_reasons: string[];
  reason?: string;
  last_seen_at?: string | null;
  created_at: string;
  updated_at: string;
};

export type ProfileFacetPolicyView = {
  active_threshold?: number;
  provisional_threshold?: number;
  candidate_threshold?: number;
  require_review_classes: string[];
  class_budgets: Record<string, number>;
  default_class_budget?: number;
  max_facets?: number;
  pollution_requires_review?: boolean;
};

export type ProfileFacetAuditEntryView = {
  audit_id: string;
  action: string;
  facet_id: string;
  source_memory_id?: string | null;
  before_state?: string | null;
  after_state?: string | null;
  before_user_state?: string | null;
  after_user_state?: string | null;
  reason?: string | null;
  source?: string;
  created_at: string;
};

export type ProfileFacetListResponse = {
  policy?: ProfileFacetPolicyView;
  items: ProfileFacetView[];
};

export type ProfileFacetGovernanceRequest = {
  action: string;
  reason?: string | null;
  source?: string;
};

export type ProfileFacetGovernanceResponse = {
  action: string;
  facet: ProfileFacetView;
  status?: string;
  message?: string;
  audit_entry?: ProfileFacetAuditEntryView | null;
};

export type ProfileFacetRebuildRequest = {
  source?: string;
};

export type ProfileFacetRebuildResponse = {
  status?: string;
  source?: string;
  facet_count?: number;
  updated_count?: number;
  facets: ProfileFacetView[];
  audit_entry?: ProfileFacetAuditEntryView | null;
};

export type ProfileFacetAuditResponse = {
  items: ProfileFacetAuditEntryView[];
};

export type MemoryMaintenanceRequest = {
  dry_run?: boolean;
  policy?: string | null;
  layer_id?: string | null;
  limit?: number | null;
  source?: string;
  run_reflection_due_jobs?: boolean | null;
};

export type MemoryMaintenanceAutomationRequest = {
  force_run?: boolean;
};

export type MemoryMaintenanceResponse = {
  run_id: string;
  status?: string;
  dry_run?: boolean;
  policy?: string;
  layer_id?: string | null;
  source?: string;
  update_queue_pending?: number;
  update_queue_drained?: number;
  reflection_jobs_due?: number;
  reflection_jobs_run?: number;
  reflection_entries_written?: number;
  governance?: MemoryGovernanceBatchResponse;
  health_before?: MemoryHealthResponse | null;
  health_after?: MemoryHealthResponse | null;
  actions_executed: Record<string, number>;
  skipped_actions: Record<string, number>;
  errors: string[];
  started_at: string;
  finished_at: string;
};

export type MemoryMaintenanceAutomationStatusResponse = {
  enabled?: boolean;
  last_run_at?: string | null;
  last_status?: string | null;
  last_reason?: string | null;
  last_run_id?: string | null;
  last_counts: Record<string, unknown>;
  last_error_count?: number;
  last_errors: string[];
  next_run_at?: string | null;
  tick_seconds?: number;
  interval_seconds?: number;
  min_idle_seconds?: number;
  dry_run?: boolean;
  execute?: boolean;
  policy?: string;
  layer_id?: string | null;
  limit?: number;
  run_reflection_due_jobs?: boolean;
};

export type MemoryMaintenanceAutomationRunResponse = {
  ran?: boolean;
  reason?: string;
  next_run_at?: string | null;
  report?: MemoryMaintenanceResponse | null;
};

export type MemoryFlushRequest = {
  thread_id?: string | null;
};

export type MemoryOnboardingRequest = {
  workspace_path?: string | null;
  thread_id?: string | null;
  force?: boolean;
  source?: string;
};

export type MemoryOnboardingFileView = {
  relative_path: string;
  kind?: string;
  size_chars?: number;
  included_chars?: number;
  truncated?: boolean;
  content_preview?: string;
};

export type MemoryOnboardingResponse = {
  accepted?: boolean;
  status?: string;
  reason?: string | null;
  workspace_path?: string;
  thread_id?: string | null;
  store_id?: string;
  layer_id?: string;
  category?: string;
  files: MemoryOnboardingFileView[];
  review_ids: string[];
  written_memory_ids: string[];
  stable_snapshot_refresh_recommended?: boolean;
  created_at: string;
};

export type MemoryCandidateAuditEntryView = {
  audit_id: string;
  action: string;
  reason: string;
  layer_id?: string | null;
  store_id?: string | null;
  category?: string;
  candidate_preview?: string;
  quality_score?: number;
  quality_decision?: string;
  blockers: string[];
  confidence?: number;
  salience?: number;
  priority?: number;
  evidence_count?: number;
  evidence_refs: string[];
  source_thread_id?: string | null;
  source_polluted?: boolean;
  pollution_reasons: string[];
  target_id?: string | null;
  supersedes: string[];
  conflicts_with: string[];
  created_at: string;
};

export type MemoryPollutionMarkerView = {
  marker_id: string;
  thread_id: string;
  source_kind?: string;
  source_id?: string | null;
  tool_name?: string | null;
  reason?: string;
  evidence_ref?: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
};

export type SelfUpgradeBacklogItemView = {
  item_id: string;
  domain: string;
  severity?: string;
  title: string;
  summary?: string;
  metric?: string | null;
  count?: number;
  recommendation?: string;
  metadata: Record<string, unknown>;
};

export type SelfUpgradeDomainHealthView = {
  domain_id: string;
  label: string;
  status?: string;
  score?: number;
  enabled?: boolean;
  metrics: Record<string, number | string | boolean>;
  issues: string[];
  recommendations: string[];
};

export type SelfUpgradeHealthResponse = {
  mode?: string;
  status?: string;
  score?: number;
  fingerprint?: string;
  domains: SelfUpgradeDomainHealthView[];
  backlog: SelfUpgradeBacklogItemView[];
  recommendations: string[];
  generated_at: string;
};

export type MemoryFlushResponse = {
  thread_id?: string | null;
  candidates_seen?: number;
  entries_written?: number;
  review_items_created?: number;
  entries_skipped?: number;
  facts_removed?: number;
  errors: string[];
  written_memory_ids: string[];
  review_ids: string[];
  candidate_audit: MemoryCandidateAuditEntryView[];
};

export type MemoryReviewDecisionRequest = {
  reason?: string | null;
};

export type MemoryReviewBatchRequest = {
  approve?: string[];
  reject?: string[];
};

export type MemoryReviewBatchResponse = {
  approved: string[];
  rejected: string[];
  errors: string[];
};

export type MemoryAdminExportView = {
  stores: Record<string, unknown>;
  review_queue: Record<string, unknown>[];
  providers: Record<string, unknown>[];
  archive_turn_count?: number;
};

export type MemoryAdminImportRequest = {
  stores?: Record<string, unknown>;
  review_queue?: Record<string, unknown>[];
};

export type MemoryAdminImportResponse = {
  entries_imported?: number;
  review_items_created?: number;
};

export type MemoryAdminAuditView = {
  snapshot: Record<string, unknown>;
  pending_review_count?: number;
  conflict_count?: number;
  staleness_count?: number;
  health: Record<string, unknown>;
  providers: Record<string, unknown>[];
  candidate_audit: MemoryCandidateAuditEntryView[];
  pollution_markers: MemoryPollutionMarkerView[];
  recall_benchmark_suites: MemoryRecallBenchmarkSuiteView[];
  recall_benchmark_runs: MemoryRecallBenchmarkRunView[];
};

export type MemoryConflictResolveRequest = {
  action?: string;
};

export type MemoryProviderAdminResponse = {
  items: MemoryProviderView[];
};

export type ReflectionJobAdminResponse = {
  items: ReflectionJobView[];
};

export type ReflectionJobView = {
  job_id: string;
  name: string;
  schedule_kind: string;
  target_store_id: string;
  enabled: boolean;
  system_managed: boolean;
  template: string;
  instructions?: string | null;
  source_query?: string | null;
  interval_seconds?: number | null;
  cron?: string | null;
  next_run_at?: string | null;
  last_run_at?: string | null;
  last_status?: string | null;
};

export type ReflectionJobCreateRequest = {
  job_id: string;
  name: string;
  schedule_kind: string;
  target_store_id?: string;
  template?: string;
  instructions?: string | null;
  source_query?: string | null;
  interval_seconds?: number | null;
  cron?: string | null;
};

export type ReflectionJobRunView = {
  job_id: string;
  status: string;
  entries_written: number;
  archive_hits: number;
  summary: string;
  written_entries: MemoryEntryView[];
};

export type ScheduledTaskScheduleView = {
  kind: string;
  display: string;
  interval_seconds?: number | null;
  cron?: string | null;
  run_at?: string | null;
};

export type ScheduledTaskView = {
  task_id: string;
  name: string;
  prompt: string;
  schedule: ScheduledTaskScheduleView;
  enabled: boolean;
  status: string;
  system_managed?: boolean;
  thread_id?: string | null;
  execution_mode?: string;
  selected_model?: string | null;
  selected_profile?: string | null;
  selected_reasoning_effort?: string | null;
  promoted_capabilities: string[];
  max_runs?: number | null;
  run_count?: number;
  missed_run_policy?: string;
  delivery: Record<string, unknown>;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  next_run_at?: string | null;
  last_run_at?: string | null;
  last_status?: string | null;
  last_error?: string | null;
  last_execution_id?: string | null;
};

export type ScheduledTaskExecutionView = {
  execution_id: string;
  task_id: string;
  thread_id: string;
  run_id?: string | null;
  status: string;
  started_at: string;
  completed_at?: string | null;
  summary?: string;
  error?: string | null;
  output_path?: string | null;
  metadata: Record<string, unknown>;
};

export type ScheduledTaskCreateRequest = {
  task_id?: string | null;
  name: string;
  prompt: string;
  schedule: string;
  enabled?: boolean;
  thread_id?: string | null;
  execution_mode?: string;
  selected_model?: string | null;
  selected_profile?: string | null;
  selected_reasoning_effort?: string | null;
  promoted_capabilities?: string[];
  max_runs?: number | null;
  delivery?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
};

export type ScheduledTaskUpdateRequest = {
  name?: string | null;
  prompt?: string | null;
  schedule?: string | null;
  enabled?: boolean | null;
  thread_id?: string | null;
  execution_mode?: string | null;
  selected_model?: string | null;
  selected_profile?: string | null;
  selected_reasoning_effort?: string | null;
  promoted_capabilities?: string[] | null;
  max_runs?: number | null;
  delivery?: Record<string, unknown> | null;
  metadata?: Record<string, unknown> | null;
};

export type ScheduledTaskRunView = {
  task: ScheduledTaskView;
  execution?: ScheduledTaskExecutionView | null;
  ran: boolean;
  reason?: string | null;
};

export type ScheduledTaskAutomationStatusResponse = {
  enabled?: boolean;
  tick_seconds?: number;
  max_due_per_tick?: number;
  task_count?: number;
  enabled_task_count?: number;
  due_count?: number;
  running_count?: number;
  failed_count?: number;
  next_run_at?: string | null;
  last_run_at?: string | null;
  last_execution_id?: string | null;
  last_status?: string | null;
  last_error?: string | null;
  recent_executions: ScheduledTaskExecutionView[];
  reason?: string;
};

export type ScheduledTaskAutomationRunResponse = {
  status: ScheduledTaskAutomationStatusResponse;
  ran_count?: number;
  skipped_count?: number;
  results: ScheduledTaskRunView[];
  reason?: string;
};

export type ScheduledTaskAdminResponse = {
  items: ScheduledTaskView[];
};

export type ScheduledTaskExecutionResponse = {
  items: ScheduledTaskExecutionView[];
};

export type CapabilityDependencyView = {
  kind: string;
  name: string;
  required?: boolean;
  details: Record<string, unknown>;
};

export type TypedApprovalPolicyView = {
  mode?: string;
  risk_category?: string | null;
  requires_network?: boolean;
  scope?: string | null;
};

export type CapabilityHealthView = {
  status?: string;
  message?: string | null;
  checked_at?: string | null;
  details: Record<string, unknown>;
};

export type CapabilityResourceView = {
  resource_id: string;
  title: string;
  description?: string;
  server_id?: string | null;
  path?: string | null;
  metadata: Record<string, unknown>;
  discovery_source?: string;
  supports_read?: boolean;
  uri?: string | null;
  mime_type?: string | null;
};

export type CapabilityPromptView = {
  prompt_id: string;
  title: string;
  description?: string;
  server_id?: string | null;
  arguments: string[];
  metadata: Record<string, unknown>;
  discovery_source?: string;
  supports_render?: boolean;
  input_schema: Record<string, unknown>;
};

export type ExtensionStatusView = {
  server_id: string;
  source_kind?: string;
  status: string;
  description?: string;
  error?: string | null;
  tool_names: string[];
  transport_kind?: string | null;
  startup_policy?: string | null;
  refresh_policy?: string | null;
  enabled?: boolean;
  tool_count?: number;
  resource_count?: number;
  prompt_count?: number;
  connected?: boolean;
  ready?: boolean;
  auth_required?: boolean;
  refresh_owner?: string | null;
  last_started_at?: string | null;
  last_refreshed_at?: string | null;
  backoff_until?: string | null;
  reconnect_count?: number;
  diagnostics: string[];
  discovery_source?: string;
  metadata: Record<string, unknown>;
  config_source?: string | null;
};

export type McpServerView = {
  server_id: string;
  source_kind?: string;
  status: string;
  description?: string;
  error?: string | null;
  tool_names: string[];
  transport_kind?: string | null;
  startup_policy?: string | null;
  refresh_policy?: string | null;
  enabled?: boolean;
  tool_count?: number;
  resource_count?: number;
  prompt_count?: number;
  connected?: boolean;
  ready?: boolean;
  auth_required?: boolean;
  refresh_owner?: string | null;
  last_started_at?: string | null;
  last_refreshed_at?: string | null;
  backoff_until?: string | null;
  reconnect_count?: number;
  diagnostics: string[];
  discovery_source?: string;
  metadata: Record<string, unknown>;
  config_source?: string | null;
};

export type McpConfigOverviewView = {
  config_path: string;
  server_count?: number;
  enabled_count?: number;
  ready_count?: number;
  auth_required_count?: number;
  disabled_count?: number;
  failed_count?: number;
  hidden_from_model_count?: number;
};

export type McpServerBatchUpsertRequest = {
  config_text: string;
};

export type McpServerBatchUpsertView = {
  status: string;
  config_path: string;
  upserted: string[];
  servers: McpServerView[];
  reload: Record<string, unknown>;
  diagnostics: string[];
};

export type McpServerDeleteView = {
  status: string;
  server_id: string;
  deleted: boolean;
  config_path: string;
  servers: McpServerView[];
  reload: Record<string, unknown>;
};

export type McpServerToolsView = {
  server_id: string;
  status: string;
  tool_names: string[];
  tool_count?: number;
  resource_count?: number;
  prompt_count?: number;
  discovery_source?: string;
};

export type McpResourceContentView = {
  resource_id: string;
  title: string;
  description?: string;
  server_id?: string | null;
  path?: string | null;
  metadata: Record<string, unknown>;
  discovery_source?: string;
  supports_read?: boolean;
  uri?: string | null;
  mime_type?: string | null;
  content?: string | null;
};

export type McpPromptRenderView = {
  prompt_id: string;
  title: string;
  description?: string;
  server_id?: string | null;
  arguments: string[];
  metadata: Record<string, unknown>;
  discovery_source?: string;
  supports_render?: boolean;
  input_schema: Record<string, unknown>;
  rendered: string;
  provided_arguments: Record<string, unknown>;
};

export type McpServerProvenanceView = {
  server_id: string;
  provenance: string;
  description?: string;
  transport_kind: string;
  startup_policy?: string | null;
  refresh_policy?: string | null;
  approval_policy?: string | null;
  tool_prefix?: string | null;
  collision_policy?: string | null;
  tool_allowlist: string[];
  tool_allowlist_active?: boolean;
  tool_denylist: string[];
  oauth: Record<string, unknown>;
  env_resolution: Record<string, unknown>;
  header_templates: Record<string, unknown>;
  resource_policy: Record<string, unknown>;
  prompt_policy: Record<string, unknown>;
  reconnect_policy: Record<string, unknown>;
  healthcheck: Record<string, unknown>;
  connection_config: Record<string, unknown>;
};

export type LinkPreviewView = {
  url: string;
  hostname: string;
  title?: string | null;
  description?: string | null;
  preview_enabled?: boolean;
  preview_status?: string;
};

export type SubagentEventView = {
  job_id: string;
  parent_thread_id: string;
  parent_run_id?: string | null;
  event: string;
  timestamp?: string | null;
  status?: string | null;
  summary?: string | null;
  error?: string | null;
  tool_name?: string | null;
  display_name?: string | null;
  child_thread_id?: string | null;
  child_run_id?: string | null;
};

export type SubagentMessagePreviewView = {
  role: string;
  content_preview?: string;
  tool_call_count?: number;
  tool_result_count?: number;
};

export type SubagentApprovalSummaryView = {
  pending_approval?: string | null;
  request_id?: string | null;
  thread_id?: string | null;
  turn_id?: string | null;
  reason?: string | null;
  action_kind?: string | null;
  requested_permissions: string[];
  tool_name?: string | null;
  approval_profile?: string | null;
  risk_category?: string | null;
  capability_group?: string | null;
};

export type SubagentToolEvidenceView = {
  tool_call_id?: string | null;
  message_id?: string | null;
  name?: string | null;
  display_name?: string | null;
  source_kind?: string | null;
  source_id?: string | null;
  capability_group?: string | null;
  tool_execution_mode?: string | null;
  status?: string | null;
  args_keys: string[];
  has_result?: boolean;
  result_char_count?: number;
  started_at?: string | null;
  completed_at?: string | null;
  duration_ms?: number | null;
};

export type SubagentTaskView = {
  task_id: string;
  batch_id?: string | null;
  parent_thread_id: string;
  parent_run_id?: string | null;
  child_thread_id?: string | null;
  child_run_id?: string | null;
  status: string;
  assigned_profile: string;
  delegation_depth: number;
  workspace_mode?: string | null;
  cancel_requested?: boolean;
  depends_on_task_ids: string[];
  dependency_state?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  timeout_at?: string | null;
  error?: string | null;
  summary?: string | null;
  requested_tool_names: string[];
  allowed_tool_names: string[];
  messages: SubagentMessagePreviewView[];
  recent_tool_activity: SubagentToolEvidenceView[];
  recent_events: SubagentEventView[];
  artifacts: ArtifactRefView[];
  approval_payload?: SubagentApprovalSummaryView | null;
};

export type SubagentDependencyEdgeView = {
  source_task_id: string;
  target_task_id: string;
  status: string;
  source_status?: string | null;
};

export type SubagentDependencyGraphView = {
  parent_thread_id: string;
  parent_run_id?: string | null;
  tasks: SubagentTaskView[];
  edges: SubagentDependencyEdgeView[];
  ready_task_ids: string[];
  waiting_task_ids: string[];
  blocked_task_ids: string[];
  missing_dependency_task_ids: string[];
};

export type ProcessInputEventView = {
  text_preview?: string;
  submitted?: boolean;
  byte_count?: number;
  created_at: string;
};

export type ProcessSessionView = {
  session_id: string;
  thread_id: string;
  command: string;
  cwd: string;
  backend?: string;
  backend_id?: string;
  backend_label?: string;
  interactive?: boolean;
  pty?: boolean;
  pid?: number | null;
  status: string;
  exit_code?: number | null;
  detached?: boolean;
  log_cursor?: number;
  stdin_closed?: boolean;
  last_stdin_at?: string | null;
  last_signal?: string | null;
  last_signal_at?: string | null;
  columns?: number | null;
  rows?: number | null;
  input_history: ProcessInputEventView[];
  started_at: string;
  completed_at?: string | null;
  log_path: string;
  last_output?: string;
};

export type ProcessLogView = {
  session_id: string;
  status: string;
  output: string;
  total_lines: number;
  showing: string;
  next_offset: number;
  start_offset?: number;
  backend?: string;
  incremental?: boolean;
};

export type ProcessStdinRequest = {
  data: string;
  submit?: boolean;
};

export type ProcessResizeRequest = {
  columns: number;
  rows: number;
};

export type ProcessSpawnRequest = {
  command: string;
  cwd?: string;
  env?: Record<string, string>;
};

export type TerminalBackendCapabilitiesView = {
  kind?: string;
  backend_id?: string;
  label?: string;
  interactive?: boolean;
  persistent_sessions?: boolean;
  pty?: boolean;
  stdin?: boolean;
  incremental_log?: boolean;
  interrupt?: boolean;
  remote?: boolean;
  isolated?: boolean;
  configured?: boolean;
  executable?: boolean;
  launch_mode?: string;
  workspace_sync?: string;
  required_config: string[];
  missing_config: string[];
  required_executables: string[];
  missing_executables: string[];
  env_passthrough: string[];
  env_prefix_passthrough: string[];
  notes: string[];
};

export type ToolCatalogEntryView = {
  capability_id: string;
  name: string;
  display_name: string;
  summary: string;
  source_kind: string;
  source_id: string;
  capability_group: string;
  visibility: string;
  deferred?: boolean;
  stability?: string;
  risk_category?: string | null;
  approval?: TypedApprovalPolicyView | null;
  resources: CapabilityResourceView[];
  prompts: CapabilityPromptView[];
  dependencies: CapabilityDependencyView[];
  provenance: Record<string, unknown>;
  health?: CapabilityHealthView;
};

export type PluginView = {
  plugin_id: string;
  enabled?: boolean;
  source_path?: string | null;
  skill_roots: string[];
  tool_count?: number;
  tool_names: string[];
  resources: CapabilityResourceView[];
  prompts: CapabilityPromptView[];
  memory_providers: Record<string, unknown>[];
  memory_provider_count?: number;
  catalog_metadata: Record<string, unknown>;
  discovery_source?: string;
};

export type PluginCatalogEntryView = {
  plugin_id: string;
  name: string;
  description?: string;
  source: string;
  source_kind?: string;
  version?: string | null;
  author?: string | null;
  homepage?: string | null;
  tags: string[];
  trust_level?: string | null;
  registry_id?: string | null;
  registry_name?: string | null;
  registry_source?: string | null;
  registry_kind?: string | null;
  installed?: boolean;
  enabled?: boolean;
  installable?: boolean;
  skill_count?: number;
  tool_count?: number;
  mcp_server_count?: number;
  resource_count?: number;
  prompt_count?: number;
  memory_provider_count?: number;
  skill_roots: string[];
  tool_names: string[];
  mcp_servers: string[];
  memory_providers: string[];
  permissions: string[];
  catalog_metadata: Record<string, unknown>;
  discovery_source?: string;
};

export type PluginRegistryView = {
  registry_id: string;
  name: string;
  source: string;
  source_kind: string;
  enabled?: boolean;
  readonly?: boolean;
  trust_level?: string | null;
  entry_count?: number;
  cached?: boolean;
  cache_path?: string | null;
  error?: string | null;
  diagnostics: string[];
  config_path?: string | null;
  last_checked_at?: string | null;
};

export type PluginRegistryUpsertRequest = {
  source: string;
  registry_id?: string | null;
  name?: string | null;
  enabled?: boolean;
  trust_level?: string | null;
};

export type PluginRegistryUpsertView = {
  status: string;
  config_path: string;
  registry: PluginRegistryView;
  registries: PluginRegistryView[];
  catalog: PluginCatalogEntryView[];
};

export type PluginRegistryDeleteView = {
  status: string;
  registry_id: string;
  deleted: boolean;
  config_path: string;
  registries: PluginRegistryView[];
  catalog: PluginCatalogEntryView[];
};

export type PluginInstallRequest = {
  source: string;
  plugin_id?: string | null;
  enable?: boolean;
  force?: boolean;
};

export type PluginInstallView = {
  plugin_id: string;
  installed: boolean;
  enabled: boolean;
  source: string;
  path: string;
  config_path: string;
  skill_roots: string[];
  tool_count?: number;
  bundled_mcp_servers: string[];
  reload: Record<string, unknown>;
  plugins: PluginView[];
};

export type McpPromptRenderRequest = {
  arguments?: Record<string, unknown>;
};
